### ISSUE TITLE
Genomic Workflow Output manifest CLI incorporation

### ISSUE THREAD

**Issue by gsantia** [kids-first/kf-lib-data-ingest#625]
A lot of work was done in the Study Creator to allow analysts to ingest genomic workflow output data into the Dataservice ([details here](https://github.com/kids-first/kf-api-study-creator/issues/491)). The plan was to allow the user to upload a GWO manifest and then hit an 'ingest' button which would run through the process. This has not been implemented in production because the complicated nature of this process is really too much for just a simple button push (monitoring and error handling etc is required for good outcomes).

In reality this turned out to be a task of adding new functionality to the ingest library and then stapling it to the Study Creator API. Instead of letting this functionality languish in a purgatory between backend and frontend, it'd be nice to add it to the ingest library CLI tool as another option. This would allow for a far more fine-tuned approach than just pushing a button, but wouldn't require the same heavy time investment to create a user-friendly frontend environment.

Here's my current idea for steps:

- [ ] Talk to end users (analysts) about how they'd want this new functionality to look and work, and what kinds of options would be useful
- [ ] Take this information and create an RFC and allow for everyone to think about it and comment and hopefully come to some type of consensus
- [ ] Implement the desired functionality
- [ ] Have users test it out and perform basic QA
- [ ] Release to production

**Comment by znatty22** [comment]
cc @fiendish @chris-s-friedman @youngnm @nicolevasilevsky @Christina-J-Diaz

**Comment by fiendish** [comment]
After step 2 is done this needs to be converted into more concrete actions.

**Comment by gsantia** [comment]
> After step 2 is done this needs to be converted into more concrete actions.

yeah, absolutely. any thoughts?
